### ISSUE TITLE
Can not build compiler for CentOs

### ISSUE THREAD

**Issue by person2713** [catenax-ng/product-edc#56] opened 2022-04-27 17:06 UTC
Hello, I have tried to build compiler according the instruction https://thrift.apache.org/docs/install/centos.html
But it doesn't work, I got error for version 17:
```
thrift 0.17.0

Building C (GLib) Library .... : no
Building C++ Library ......... : no
Building D Library ........... : no
Building Dart Library ........ : no
Building .NET Standard Library : no
Building Erlang Library ...... : no
Building Go Library .......... : no
Building Haxe Library ........ : no
Building Java Library ........ : yes
Building Kotlin Library ...... : yes
Building Lua Library ......... : no
Building NodeJS Library ...... : no
Building Perl Library ........ : no
Building PHP Library ......... : no
Building Python Library ...... : no
Building Py3 Library ......... : no
Building Ruby Library ........ : no
Building Rust Library ........ : no
Building Swift Library ....... : no

Java Library:
   Using gradle .............. : /opt/gradle/gradle-6.9.2/bin/gradle
   Using java ................ : java
   Using javac ............... : javac
   Using Gradle version ...... : Gradle 6.9.2
   Using java version ........ : openjdk version "11.0.14.1" 2022-02-08 LTS

Kotlin (Test Only) Library:
   Using gradlew ............. : lib/kotlin/gradlew
   Using java ................ : java
   Using javac ............... : javac
./configure: line 28879: lib/kotlin/gradlew: No such file or directory
   Using Gradle version ...... : 
   Using java version ........ : openjdk version "11.0.14.1" 2022-02-08 LTS

```
```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :copyDependencies
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: release version 8 not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
for version 16:
```
thrift 0.16.0

Building C (GLib) Library .... : no
Building C++ Library ......... : no
Building Common Lisp Library.. : no
Building D Library ........... : no
Building Dart Library ........ : no
Building .NET Standard Library : no
Building Erlang Library ...... : no
Building Go Library .......... : no
Building Haxe Library ........ : no
Building Java Library ........ : yes
Building Lua Library ......... : no
Building NodeJS Library ...... : no
Building Perl Library ........ : no
Building PHP Library ......... : no
Building Python Library ...... : no
Building Py3 Library ......... : no
Building Ruby Library ........ : no
Building Rust Library ........ : no
Building Swift Library ....... : no

Java Library:
   Using gradlew ............. : lib/java/gradlew
   Using java ................ : java
   Using javac ............... : javac
   Using Gradle version ...... : Gradle 5.6.4
   Using java version ........ : openjdk version "11.0.14.1" 2022-02-08 LTS
```
```
Making all in java
make[3]: Entering directory `/thrift-0.16.0/lib/java'
./gradlew  assemble \
	-Prelease=true \
	-Pthrift.version=0.16.0 \
	--console=plain
> Task :copyDependencies
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: release version 8 not supported
```
I will appreciate any help.

**Comment by DominikPinsel** [comment] 2022-04-28 07:50
Thanks for reporting an issue. I'm not understanding the problem yet. Also it looks like this is a Gradle issue, and this project is build with Maven. Maybe you can add steps to reproduce, so that I have a little more context.

**Comment by denisneuling** [comment] 2022-04-28 08:20
Hello @person2713, it seems like your issue relates to Apache Thrift, so I'd rather expect this issue to be filed at the concerning [Jira issue tracker](https://issues.apache.org/jira/projects/THRIFT/issues/THRIFT-3877?filter=allopenissues) as their [developers portal](https://thrift.apache.org/developers) suggests.

Closing this issue since it does not relate to our project.

**Closed by denisneuling** 2022-04-28 08:20 UTC
Labels: bug
